---
title: "DDP Shiny App-Machine Learning-"
author: "jguzmant"
date: "7/8/2020"
output:
  ioslides_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Unsuppervised ML over MTCARS dataset

This shiny app is intended to show an application of a Machine Learning unsuppervised Algorithm K-means, it shows the groups(clusters) and colours the observations according to their nearest group(cluster).

## Plot

```{r cars, warning=FALSE}
suppressMessages(library(plotly))
suppressMessages(library(tidyr))
suppressMessages(library(dplyr))
suppressMessages(library(UsingR))


data(mtcars)


clusters <- kmeans(mtcars[,c(1,3)], 3)

suppressWarnings(plot_ly(mtcars,x=~mpg,y=~disp,color=~clusters$cluster,type="scatter",mode = 'markers') %>% add_markers(x=~clusters$centers[,1],
                      y=~clusters$centers[,2],
                      type="scatter",
                      color="red",
                      marker = list(symbol = 'cross'),
                      name="Cluster Mean",
                      size=10
                      )) 


```
